[meta]
generated_by = "2.11.0"

[project]
user_env = []
session_timeout = 3600
user_session_timeout = 1296000
cache = false
persist_user_env = false
mask_user_env = false
allow_origins = ["*"]

[features]
unsafe_allow_html = false
latex = false
user_message_markdown = true
user_message_autoscroll = true
assistant_message_autoscroll = true
auto_tag_thread = true
edit_message = true
allow_thread_sharing = false
favorites = false

[features.spontaneous_file_upload]
enabled = true
accept = ["*/*"]
max_files = 20
max_size_mb = 500

[features.audio]
enabled = false
sample_rate = 24000

[features.mcp]
enabled = false

[features.mcp.sse]
enabled = true

[features.mcp.streamable-http]
enabled = true

[features.mcp.stdio]
enabled = true
allowed_executables = ["npx", "uvx"]

[UI]
name = "Siprtc Assistant"
description = "Siprtc.io MCP assistant for phone numbers, SIP users, applications, and more."
default_theme = "light"
layout = "wide"
alert_style = "modern"
confirm_new_chat = true
cot = "full"
logo_file_url = "https://siprtc.io/static/img/logo.png"
default_avatar_file_url = "https://siprtc.io/static/img/logo.png"
custom_js = "/public/siprtc.js"
custom_css = "/public/siprtc.css"
